import { execSync } from 'node:child_process';
import { readFileSync } from 'node:fs';

import Anthropic from '@anthropic-ai/sdk';

const { ANTHROPIC_API_KEY, GITHUB_TOKEN, PR_NUMBER, REPO, BASE_SHA, HEAD_SHA } =
  process.env;

const diff = execSync(
  `git diff ${BASE_SHA} ${HEAD_SHA} -- '*.ts' '*.tsx' '*.js' '*.mjs' '*.css' \
  ':!*.config.*' \
  ':!*.config.ts' \
  ':!*.config.js' \
  ':!*.config.mjs' \
  ':!tailwind.config.*' \
  ':!next.config.*' \
  ':!jest.config.*' \
  ':!eslint.config.*' \
  ':!prettier.config.*' \
  ':!postcss.config.*' \
  ':!*.d.ts'`,
  { maxBuffer: 1024 * 1024 * 10 },
).toString();

if (!diff.trim()) {
  console.log('No relevant file changes found, skipping review.');
  process.exit(0);
}

const reviewRules = readFileSync(
  new URL('../.claude/pr/review-rules.md', import.meta.url),
  'utf8',
);

const client = new Anthropic({ apiKey: ANTHROPIC_API_KEY });

const message = await client.messages.create({
  model: 'claude-opus-4-7',
  max_tokens: 2048,
  messages: [
    {
      role: 'user',
      content: `You are a senior software engineer reviewing a pull request for a Next.js + Supabase + Tailwind CSS project.

Follow these review rules strictly:

<rules>
${reviewRules}
</rules>

Format your response as GitHub-flavored Markdown.
Start with a one-line summary, then list issues grouped by severity: 🔴 Critical, 🟡 Warning, 🟢 Suggestion.
If nothing notable found, say so briefly. Do not flag issues that the rules say are handled automatically (Prettier, ESLint).

<diff>
${diff.slice(0, 80000)}
</diff>`,
    },
  ],
});

const review = message.content[0].text;

const response = await fetch(
  `https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments`,
  {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: JSON.stringify({
      body: `## Claude Code Review\n\n${review}\n\n---\n*Generated by [claude-opus-4-7](https://anthropic.com)*`,
    }),
  },
);

if (!response.ok) {
  const error = await response.text();
  console.error('Failed to post comment:', error);
  process.exit(1);
}

console.log('Review posted successfully.');
