import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import React from 'react';

import { appConfig } from '@/src/app/[locale]/config';
import { ThemeProvider } from '@/src/core/context';
import type { LayoutProps, TTheme } from '@/src/core/types';
import { redirect } from '@/src/i18n/routing';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'LinkUp Chat',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }: LayoutProps) {
  const { locale: urlLocale } = await params;
  const { theme, dbLocale, messages } = await appConfig(urlLocale);

  if (dbLocale !== urlLocale) {
    redirect({
      href: {
        pathname: '/',
      },
      locale: dbLocale,
    });
  }

  return (
    <html lang={dbLocale} suppressHydrationWarning className={theme}>
      <body className={`${inter.variable} bg-main-bg font-sans antialiased`}>
        <NextIntlClientProvider
          locale={dbLocale}
          key={dbLocale}
          messages={messages}
        >
          <ThemeProvider key={theme} initialTheme={theme as TTheme}>
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
