import { execSync } from 'node:child_process';
import { readFileSync } from 'node:fs';

import Anthropic from '@anthropic-ai/sdk';

const { ANTHROPIC_API_KEY, GITHUB_TOKEN, PR_NUMBER, REPO, BASE_SHA, HEAD_SHA } =
  process.env;

const MAX_DIFF_CHARS = 80_000;

const diff = execSync(
  `git diff ${BASE_SHA} ${HEAD_SHA} -- '*.ts' '*.tsx' '*.js' '*.mjs' '*.css' \
  ':!*.config.*' \
  ':!*.config.ts' \
  ':!*.config.js' \
  ':!*.config.mjs' \
  ':!tailwind.config.*' \
  ':!next.config.*' \
  ':!jest.config.*' \
  ':!eslint.config.*' \
  ':!prettier.config.*' \
  ':!postcss.config.*' \
  ':!*.d.ts'`,
  { maxBuffer: 1024 * 1024 * 10 },
).toString();

if (!diff.trim()) {
  console.log('No relevant file changes found, skipping review.');
  process.exit(0);
}

let reviewRules;
let promptTemplate;

try {
  reviewRules = readFileSync(
    new URL('../../.claude/pr/review-rules.md', import.meta.url),
    'utf8',
  );
} catch {
  console.error(
    'Failed to read review-rules.md: expected at .claude/pr/review-rules.md',
  );
  process.exit(1);
}

try {
  promptTemplate = readFileSync(
    new URL('./review-prompt.md', import.meta.url),
    'utf8',
  );
} catch {
  console.error(
    'Failed to read review-prompt.md: expected at scripts/pr/review-prompt.md',
  );
  process.exit(1);
}

if (!promptTemplate.includes('{{RULES}}')) {
  throw new Error('review-prompt.md is missing {{RULES}} placeholder');
}

if (!promptTemplate.includes('{{DIFF}}')) {
  throw new Error('review-prompt.md is missing {{DIFF}} placeholder');
}

const truncatedDiff = diff.slice(0, MAX_DIFF_CHARS);

const prompt = promptTemplate
  .replaceAll('{{RULES}}', () => reviewRules)
  .replaceAll('{{DIFF}}', () => truncatedDiff);

const client = new Anthropic({ apiKey: ANTHROPIC_API_KEY });

const message = await client.messages.create({
  model: 'claude-opus-4-7',
  max_tokens: 2048,
  messages: [{ role: 'user', content: prompt }],
});

const review = message.content[0].text;

const response = await fetch(
  `https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments`,
  {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: JSON.stringify({
      body: `## Claude Code Review\n\n${review}\n\n---\n*Generated by [claude-opus-4-7](https://anthropic.com)*`,
    }),
  },
);

if (!response.ok) {
  const error = await response.text();
  console.error('Failed to post comment:', error);
  process.exit(1);
}

console.log('Review posted successfully.');
